MODEL:
  META_ARCHITECTURE: "SEPSNet"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  BASIS_MODULE:
    LOSS_ON: False
    NORM: "GN"
    NUM_CLASSES: 8
    ANN_SET: cityscapes
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: False
    NUM_CLASSES: 8
  SEM_SEG_HEAD:
    NUM_CLASSES: 12
DATASETS:
  TRAIN: ("cityscapes_fine_instance_seg_train",)
  TEST: ("cityscapes_fine_instance_seg_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.01 
  STEPS: (25000, 40000, 50000)
  MAX_ITER: 55000
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048
TEST:
  EVAL_PERIOD: 25000
