_BASE_: "Base-Panoptic_city.yaml"
MODEL:
  WEIGHTS: "weights/FCOS_MS_R_101_2x.pth"
  RESNETS:
    DEPTH: 101
  SEPSNET:
    CONTOUR_LOSS_ON: True
    CONTOUR_WEIGHT: 0.2
    IOU_LOSS_ON: True
    IOU_PREDICT: True
    CONTOUR_PREDICT: True
    CONTOUR_STUFF: True
    CONTOUR_AUXILIARY: True
    CLASS_CONFIDENCE_WEIGHT: 0.8
  BASIS_MODULE:
    ONE_BASIS_CONTOUR_ON: True
    NUM_BASES: 5
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.01  
  STEPS: (25000, 40000, 50000)
  MAX_ITER: 55000
OUTPUT_DIR: "output/CityScapes_R_101"
TEST:
  EVAL_PERIOD: 60000
