_BASE_: "Base-Panoptic.yaml"
MODEL:
  WEIGHTS: "weights/FCOS_MS_X_101_32x8d_2x.pth"
  RESNETS:
    DEPTH: 101
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    STRIDE_IN_1X1: False
  SEPSNET:
    CONTOUR_LOSS_ON: True
    CONTOUR_WEIGHT: 0.2
    IOU_LOSS_ON: True
    IOU_PREDICT: True
    CONTOUR_PREDICT: True
    CONTOUR_STUFF: True
    CONTOUR_AUXILIARY: True
    CLASS_CONFIDENCE_WEIGHT: 0.9
  BASIS_MODULE:
    BASIS_CONTOUR_ON: True
    ONE_BASIS_CONTOUR_ON: True
    NUM_BASES: 5
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.5
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.01 
  STEPS: (120000, 420000, 500000)
  MAX_ITER: 600000
OUTPUT_DIR: "output/COCO_X_101"
TEST:
  EVAL_PERIOD: 60000
